/**
 * @file Librosa parity tests for the STFT pipeline.
 *
 * Bin-for-bin comparison of our STFT magnitudes against librosa
 * fixtures (generated by `tests/make_fixtures.py` +
 * `tests/fixture_helpers.py`). Tolerance is 1% of per-frame peak,
 * which forgives int16 quantization and float order-of-operations
 * drift while catching real algorithmic divergence.
 *
 * Covers three signal classes — stationary tone (sine), non-stationary
 * sweep, and broadband noise — at three durations (1s, 10s, 60s) so
 * frame-count drift over long signals stays visible.
 *
 * @author K. Seow <kseow@wisc.edu>
 * @created 2026-04-23
 * @version 0.2.0
 * @license MIT
 */

import { describe, it, expect } from 'vitest';
import { resolve } from 'node:path';

import {
	stft,
	generateSine,
	loadWavMonoInt16,
	loadFixture,
	compareToLibrosa,
	type StftFixture,
	SAMPLE_RATE,
	N_FFT,
	HOP_LENGTH,
	FIXTURE_DIR
} from './helpers';

describe('librosa parity — 440 Hz sine (stationary)', () => {
	it('matches librosa magnitudes within 1% of per-frame peak', () => {
		const fixture = loadFixture<StftFixture & { frequency_hz: number; amplitude: number }>(
			'librosa_stft_440hz.json'
		);
		expect(fixture.sample_rate).toBe(SAMPLE_RATE);
		expect(fixture.n_fft).toBe(N_FFT);
		expect(fixture.hop_length).toBe(HOP_LENGTH);

		// int16 quantization noise (~1/32768) is well below 1%.
		const samples = generateSine(fixture.frequency_hz, 1.0, fixture.sample_rate, fixture.amplitude);
		compareToLibrosa(stft(samples), fixture);
	});
});

describe('librosa parity — frequency sweep (non-stationary)', () => {
	it('matches librosa magnitudes within 1% of per-frame peak', () => {
		const fixture = loadFixture<StftFixture & { min_freq_hz: number; max_freq_hz: number }>(
			'1_second_files/sweep_1s_stft.json'
		);
		expect(fixture.sample_rate).toBe(SAMPLE_RATE);
		const { samples } = loadWavMonoInt16(resolve(FIXTURE_DIR, '1_second_files', 'sweep_1s.wav'));
		compareToLibrosa(stft(samples), fixture);
	});
});

describe('librosa parity — white noise (broadband, stochastic)', () => {
	it('matches librosa magnitudes within 1% of per-frame peak', () => {
		const fixture = loadFixture<StftFixture & { seed: number }>(
			'1_second_files/noise_1s_stft.json'
		);
		expect(fixture.sample_rate).toBe(SAMPLE_RATE);
		const { samples } = loadWavMonoInt16(resolve(FIXTURE_DIR, '1_second_files', 'noise_1s.wav'));
		compareToLibrosa(stft(samples), fixture);
	});
});

describe('librosa parity — sweep, 10 seconds (long-form drift check)', () => {
	it('matches librosa magnitudes within 1% of per-frame peak', () => {
		const fixture = loadFixture<StftFixture & { min_freq_hz: number; max_freq_hz: number }>(
			'10_second_files/sweep_10s_stft.json'
		);
		expect(fixture.sample_rate).toBe(SAMPLE_RATE);
		const { samples } = loadWavMonoInt16(
			resolve(FIXTURE_DIR, '10_second_files', 'sweep_10s.wav')
		);
		compareToLibrosa(stft(samples), fixture);
	});
});

describe('librosa parity — sweep, 60 seconds (longer-form drift check)', () => {
	it('matches librosa magnitudes within 1% of per-frame peak', () => {
		const fixture = loadFixture<StftFixture & { min_freq_hz: number; max_freq_hz: number }>(
			'60_second_files/sweep_60s_stft.json'
		);
		expect(fixture.sample_rate).toBe(SAMPLE_RATE);
		const { samples } = loadWavMonoInt16(
			resolve(FIXTURE_DIR, '60_second_files', 'sweep_60s.wav')
		);
		compareToLibrosa(stft(samples), fixture);
	});
});
