/**
 * @file Integration tests for extractWaveformData with real WAV bytes.
 *
 * Companion to `waveformData.unit.test.ts`. Where the unit tests use
 * a mocked AudioBuffer, this file feeds bytes from real WAV fixtures
 * on disk through `loadWavMono` (a Node-side stand-in for the
 * browser's `AudioContext.decodeAudioData`, which is unavailable
 * outside the browser). Catches anything that breaks at the boundary
 * between WAV decoding and the function under test.
 *
 * Two fixtures: a clean 1-second 440 Hz sine (predictable assertions)
 * and a realistic multi-signal composite (`tests/fixtures/test.wav`,
 * generated by CreateWavSounds.py).
 *
 * @author K. Seow <kseow@wisc.edu>
 * @created 2026-05-03
 * @version 0.2.0
 * @license MIT
 */

import { resolve } from 'node:path';
import { describe, it, expect } from 'vitest';
import { extractWaveformData } from '../utils/waveformData';
import { loadWavMono } from './helpers';

const MAX_POINTS = 5000;
const FIXTURE_DIR = resolve(__dirname, '../../../tests/fixtures');

// Wraps samples into the AudioBuffer shape extractWaveformData expects.
function asAudioBuffer(sampleRate: number, samples: Float32Array): AudioBuffer {
	return {
		sampleRate,
		length: samples.length,
		getChannelData: () => samples
	} as unknown as AudioBuffer;
}

describe('extractWaveformData — sine_440hz.wav (small predictable fixture)', () => {
	it('extracts the expected shape from a 1-second 440 Hz sine', () => {
		const { sampleRate, samples } = loadWavMono(resolve(FIXTURE_DIR, 'sine_440hz.wav'));
		const buf = asAudioBuffer(sampleRate, samples);

		const { waveform, minAmp, maxAmp } = extractWaveformData(buf, 0, 1);

		// Decimation cap holds.
		expect(waveform.length).toBeLessThanOrEqual(MAX_POINTS);

		// Fixture amplitude is 0.5; peaks should be near ±0.5.
		expect(maxAmp).toBeGreaterThan(0.49);
		expect(minAmp).toBeLessThan(-0.49);

		// Sine is zero-mean — catches sample-shift / endianness bugs.
		const mean = waveform.reduce((s, p) => s + p.amplitude, 0) / waveform.length;
		expect(Math.abs(mean)).toBeLessThan(0.05);

		// Time window matches what we asked for.
		expect(waveform[0].time).toBeGreaterThanOrEqual(0);
		expect(waveform.at(-1)!.time).toBeLessThan(1);

		// Timestamps strictly increase — no duplicates, no reversals.
		for (let i = 1; i < waveform.length; i++) {
			expect(waveform[i].time).toBeGreaterThan(waveform[i - 1].time);
		}

		// No NaN / Infinity / undefined leaks.
		expect(waveform.every((p) => Number.isFinite(p.amplitude))).toBe(true);
	});
});

describe('extractWaveformData — tests/fixtures/test.wav (full CreateWavSounds.py fixture)', () => {
	it('handles the realistic multi-signal file without breaking its contract', () => {
		const { sampleRate, samples } = loadWavMono(resolve(FIXTURE_DIR, 'test.wav'));
		const buf = asAudioBuffer(sampleRate, samples);
		const duration = samples.length / sampleRate;

		const { waveform, minAmp, maxAmp } = extractWaveformData(buf, 0, duration);

		// Multi-million-sample input must still respect the rendering budget.
		expect(waveform.length).toBeLessThanOrEqual(MAX_POINTS);

		// Both polarities present — guards against a silent zero-fill decode.
		expect(maxAmp).toBeGreaterThan(0);
		expect(minAmp).toBeLessThan(0);

		// All values finite.
		expect(waveform.every((p) => Number.isFinite(p.amplitude))).toBe(true);

		// Time window respected.
		expect(waveform[0].time).toBeGreaterThanOrEqual(0);
		expect(waveform.at(-1)!.time).toBeLessThanOrEqual(duration);

		// Timestamps strictly increase.
		for (let i = 1; i < waveform.length; i++) {
			expect(waveform[i].time).toBeGreaterThan(waveform[i - 1].time);
		}
	});
});
